from pathlib import Path
import re,json,hashlib
root=Path(__file__).resolve().parents[1]
p=root/'src/third_party/gifsicle/src/gifsicle.c'
s=p.read_text().split('const Clp_Option options[] = {')[1].split('\n};')[0]
entries=[]
for m in re.finditer(r'\{\s*("[^"]+"|0),\s*(\'[^\']\'|0),\s*([^,]+),\s*([^,]+),\s*([^}]+)\}',s):
 name,short,ident,typ,flags=[v.strip() for v in m.groups()]
 if name=='0': name='-'+short[1:-1]
 else:name='--'+name[1:-1]
 entries.append(dict(name=name,short=None if short=='0' else '-'+short[1:-1],parserId=ident,valueType=typ,negatable='Clp_Negate' in flags,optionalValue='Clp_Optional' in flags,repeatable=True,category='external' if ident=='COLOR_TRANSFORM_OPT' else 'cli',status='partiallySupported',reason='Embedded parser available; complete per-option platform conformance remains pending.'))
for e in entries:
 e['canonicalName']=next((x['name'] for x in entries if x['parserId']==e['parserId'] and x['name'].startswith('--')),e['name'])
 if e['parserId']=='COLOR_TRANSFORM_OPT': e.update(status='unsupported',reason='External process execution is disabled on all platforms.')
 if e['parserId']=='THREADS_OPT': e['reason']='Internal threading disabled; only --threads=1 / --no-threads accepted.'
p=root/'tool/cli/gifsicle_1_96_options.json';p.parent.mkdir(exist_ok=True)
p.write_text(json.dumps({'version':'1.96','source':'gifsicle.c options table and vendored gifsicle.1; help snapshot in upstream/help.txt','options':entries},indent=2)+'\n')
opts={e['name']:{'level':e['status'],'reason':e['reason']} for e in entries}
for e in entries:
 if e['short']:opts[e['short']]=opts[e['name']]
 if e['negatable'] and e['name'].startswith('--') and not e['name'].startswith('--no-'):opts['--no-'+e['name'][2:]]=opts[e['name']]
base=json.dumps({'gifsicleVersion':'1.96','bridgeAbiVersion':1,'options':opts,'features':['stdin','stdout','isolatedWorkspace','directFileSystemAccess','multipleInputs','generatedFiles']},separators=(',',':'))
(root/'src/bridge/capabilities.inc').write_text('/* Generated by tool/generate_cli_manifest.py. */\n#define GS_CAPABILITIES_BODY '+json.dumps(base[1:])+'\n')
(root/'lib/src/cli_manifest.dart').write_text('// Generated by tool/generate_cli_manifest.py.\nconst cliOptionNames = <String>'+json.dumps([e['name'] for e in entries])+';\n')
